fixed issue with backslash and corrected typo
cometkim/vite-plugin-relay-lite pull request #117
Opened 2024-06-17 14:37 UTC by Timothy248

fixed issues with importing on windows (replace backslash with forward slash) and corrected a typo

2024-06-17 19:07 UTC, cometkim requested changes

2024-06-17 19:07 UTC, cometkim commented on src/compile.ts
> +  return joinedPath.replace("\\", "/");
This only replaces the first match

2024-06-17 20:45 UTC, Timothy248 commented on src/compile.ts
> +  return joinedPath.replace("\\", "/");
oh shoot, i fixed it!

2024-06-17 22:04 UTC, cometkim commented
Umm... could you please avoid including unnecessary format changes?

2024-06-17 23:10 UTC, Timothy248 commented
I'm so sorry! This is my first time contributing.. Reverted the formatting. Please excuse my mistakes😅

2024-06-18 08:03 UTC, cometkim commented
No problem, it's a pretty common mistake

Thanks for reporting this

2024-06-18 12:54 UTC, Timothy248 commented
Thanks :) Can you merge this? or does it need other changes?

2024-06-18 14:37 UTC, cometkim approved these changes

2024-06-18 14:40 UTC, cometkim commented on src/compile.ts
> +  return joinedPath.replaceAll("\\", "/");
Hmm, well I guess maybe this doesn't work where there are legitimate escape paths, e.g. if the workspace path has spaces: `/My\ Workspace/project` ?

2024-06-18 14:41 UTC, cometkim commented on src/compile.ts
> +  return joinedPath.replaceAll("\\", "/");
Ah, nevermind, `\\` is escaped one

2024-06-18 14:41 UTC, merged